### PR TITLE
Updated CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by gopavasanth**
Fixed few Typos

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?

### New Feature Submissions:

1. [x] Does your submission pass build tests locally?
2. [x] Have you indented your code locally prior to submission?

### Changes to Core Features:

* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by monsij** [comment]
Hope that you have followed the contribution guidelines. Please don't make a request anywhere to get a review. One of the maintainers will get back to it within a day or so. 😃

(Powered by [GitMate.io](https://gitmate.io))

**Comment by gopavasanth** [comment]
By seeing the CONTRIBUTING.rst I found a couple of typos, I Checked with Grammarly I found this requires a sort of updates, So I made this PR to fix those common minor mistakes.

**Comment by gopavasanth** [comment]
#38

**Comment by monsij** [comment]
"@gitmate-bot rebase"

**Comment by monsij** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by monsij** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by monsij** [comment]
ack `30d0877`

**Pull request merged**
