### PR TITLE
resolved uneven card size

### PR DESCRIPTION
**Pull request by harry-hov**
Resolved Issue #40 
screenshot 56

### CODE REVIEW

**Comment by monsij** [comment]
Hope that you have followed the contribution guidelines. Please don't make a request anywhere to get a review. One of the maintainers will get back to it within a day or so. 😃

(Powered by [GitMate.io](https://gitmate.io))

**Comment by monsij** [comment]
@harry-hov : PR from a branch req

**Comment by harry-hov** [comment]
> @harry-hov : PR from a branch req
i can't understand. 
can you please explain

**Comment by monsij** [comment]
Make PRs from a branch of your forked-master

**Comment by harry-hov** [comment]
I guess i made PR from forked-master

**Comment by monsij** [comment]
Yes. Make them from a branch of it

**Comment by harry-hov** [comment]
means create another branch other than master and send PR from it?

**Comment by monsij** [comment]
Yes....look into other's PR to have an idea

**Comment by harry-hov** [comment]
sure.
and what about this PR ?

**Comment by harry-hov** [comment]
Actually I'm new to git.
Can you please tell me why you suggested to make PR from different branch

**Comment by monsij** [comment]
Check this out :

**Comment by monsij** [comment]
"@gitmate-bot rebase"

**Comment by monsij** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by monsij** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by monsij** [comment]
ack `116f3aa`

**Pull request merged**
