### PR TITLE
Revamped contributors page

### PR DESCRIPTION
**Pull request by harry-hov**
#### 3. Added new Contributor

screenshot 48

### CODE REVIEW

**Comment by monsij** [comment]
Simply Awesome @harry-hov

**Comment by harry-hov** [comment]
Thank you

**Comment by monsij** [comment]
Could you give it a try to land up somewhere like this..maybe more information helps to make it better. **Also render images dirrctly from web , instead of storing them locally in blog/static/images** Contributors

**Do mention a reference to the source you get inspired from**

**Comment by harry-hov** [comment]
Sure, I'll give it a try.
but it may take some time.

- I learned from here while ago : https://www.w3schools.com/

**Comment by monsij** [comment]
Yeah not an issue.look into the source codes of these examples. You'll get to know how to scrap data for contributers

**Comment by harry-hov** [comment]
Can you provide me the link for the same? So, I can look into their source code.

**Comment by monsij** [comment]
https://coala.io/#/getinvolved?lang=Python

**Comment by harry-hov** [comment]
I am looking forward to it. 
As it may take time. You can merge this PR for now, so others don't have to suffer from that ugly contribution page

**Comment by monsij** [comment]
"@gitmate-bot rebase"

**Comment by monsij** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by monsij** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by monsij** [comment]
ack `7206179`

**Comment by monsij** [comment]
@harry-hov : Make a PR from a branch of your fork and not from the master branch. Rest is perfect as usual 💯

**Pull request merged**
