### PR TITLE
sidebar is moved to bottom

### PR DESCRIPTION
**Pull request by harry-hov**
# What i did ??
1. Added Sidebar menu in bottom navigation bar (Important Links).
2. About Us in footer
3. Added Contact in footer

### Screen 1 

screenshot 61

### Screen 2

screenshot 62

### Screen 3

screenshot 63

### CODE REVIEW

**Comment by monsij** [comment]
Hope that you have followed the contribution guidelines. Please don't make a request anywhere to get a review. One of the maintainers will get back to it within a day or so. 😃

(Powered by [GitMate.io](https://gitmate.io))

**Comment by harry-hov** [comment]
PR regarding #58 #2

**Comment by harry-hov** [comment]
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?

### New Feature Submissions:

1. [ ] Does your submission pass build tests locally?
2. [ ] Have you indented your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you successfully ran tests with your changes locally?

**Comment by monsij** [comment]
@harry-hov : Is the bottom navigation bar moving as we scroll or is stationary. If moving,make it stationary as it will occupy less space then.

**Comment by monsij** [comment]
Also remove those contacts on the extreme right side. You can add Contact Us page though( which can be presently left blank---> maybe another issue to work upon)

**Comment by monsij** [comment]
Stationary won't take much space unless we are at the bottom of the page

**Comment by harry-hov** [comment]
> Stationary won't take much space unless we are at the bottom of the page

yeah, i did the same what you are saying. it is stationary.

**Comment by harry-hov** [comment]
> Also remove those contacts on the extreme right side. You can add Contact Us page though( which can be presently left blank---> maybe another issue to work upon)

> Also remove those contacts on the extreme right side. You can add Contact Us page though( which can be presently left blank---> maybe another issue to work upon)

i made this contact in footer for technical related issue about website. 
there is already "Contacts" page and adding another page like "contact us" will confuse people

**Comment by monsij** [comment]
@harry-hov : Can the date,time and IP address be included ( in a small font) in the bottom. You can consult @nguptaa  for it

**Comment by harry-hov** [comment]
> @harry-hov : Can the date,time and IP address be included ( in a small font) in the bottom. You can consult @nguptaa for it

i'll do it

**Comment by monsij** [comment]
Can you remove the heading for date and time. Also include ip address

**Comment by harry-hov** [comment]
ok working...

**Comment by harry-hov** [comment]
screenshot 66

**Comment by harry-hov** [comment]
screenshot 67

**Comment by monsij** [comment]
Add a screenshot.Will review it soon

**Comment by monsij** [comment]
A horizontal line after ABOUT US is missing

**Comment by harry-hov** [comment]
I did it on purpose. 
do you want me to add it again ?

**Comment by monsij** [comment]
and what was the purpose? 😄

**Comment by harry-hov** [comment]
Looks i guess :p

**Comment by monsij** [comment]
@harry-hov squash please

**Comment by monsij** [comment]
Ready to be merged😎

**Comment by monsij** [comment]
Couple of more changes required @harry-hov

1. The contributors page isn't turning up.
2. The links on the footer change to grey colour(somewhat) which isn't quite visible. Change it

**Comment by monsij** [comment]
The page isnt opening

**Comment by monsij** [comment]
Yeah orange is fine

**Comment by harry-hov** [comment]
Contributors page is working fine on my side.
Maybe you're testing it offline. Try after connecting to internet.

### Screenshots:
 
screenshot 41

screenshot 42

**Comment by monsij** [comment]
Offline wouldn't work?

**Comment by harry-hov** [comment]
Nope, it needs an internet connection to fetch profile picture and other data from GitHub.

**Comment by monsij** [comment]
Remaining problems will be solved by someone else.

**Comment by monsij** [comment]
ack `50957c5`

**Pull request merged**
