### PR TITLE
Added favicon and some additional files

### PR DESCRIPTION
**Pull request by harry-hov**
### 1, Added favicon 
favicon

 Need : Its a small change but makes site more attractive. (as i'm working on its makeover)

### 2. Changed location of main.css and added some new files
Changes are in `StudentPortal> pro1> blog> static`
files changed

 Need : These files are required to makeover and redesign some html pages. (may be unfinished, but does not affect working of project).
Why I'm pushing this now? so everyone will get new location of main.css

### 3. Typo error
in settings.py, line no. 131
`bootstrp4 -> bootstrap4` 
Need : because without this fix project is not working on localhost. So in order run it on localhost i fix this.

### CODE REVIEW

**Comment by monsij** [comment]
Hope that you have followed the contribution guidelines :-)

(Powered by [GitMate.io](https://gitmate.io))

**Comment by harry-hov** [comment]
PR regarding #2

**Comment by harry-hov** [comment]
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
Yes, I did

### New Feature Submissions:

1. [ ] Does your submission pass build tests locally?
Yes
2. [ ] Have you indented your code locally prior to submission?
Yes

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
Yes
* [ ] Have you successfully ran tests with your changes locally?
Yes, it ran without any issue.

**Comment by monsij** [comment]
The local host is working fine right @harry-hov

**Comment by monsij** [comment]
With some more screenshots of the new layout , this PR will be ready to get merged✌

**Comment by harry-hov** [comment]
yeah, i checked 
it is working fine

**Comment by monsij** [comment]
@harry-hov. Squash all your commits into one.Give it a suitable message in an imperative mood.

**Comment by harry-hov** [comment]
new layout is still in progress, thats why i didnt pushed it in this PR

> With some more screenshots of the new layout , this PR will be ready to get merged✌

here it is
new_lay

**Comment by monsij** [comment]
Ok fine. Just squash up your commits

**Comment by harry-hov** [comment]
> @harry-hov. Squash all your commits into one.Give it a suitable message in an imperative mood.

it means making patch ?

**Comment by monsij** [comment]
Look [here](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git)

**Comment by harry-hov** [comment]
its my first encounter with rebase. what to do after opening rebase editor. type a new commit msg ? @monsij

**Comment by monsij** [comment]
Yes.after you have all your changes under 1 commit, give it a short title

**Comment by harry-hov** [comment]
and after giving short title, send PR again?

**Comment by monsij** [comment]
This same PR

**Comment by harry-hov** [comment]
so its done @monsij ?
i did it right?

**Comment by monsij** [comment]
@harry-hov : henceforth make PR from a branch of your fork . This time its fine. 😁

**Comment by monsij** [comment]
ack `514ac79`

**Comment by monsij** [comment]
"@gitmate-bot rebase"

**Comment by monsij** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by monsij** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by monsij** [comment]
ack `514ac79`

**Comment by monsij** [comment]
ack `514ac79`

**Comment by harry-hov** [comment]
learned a lot from this like about rebase and squash. 
Thank you @monsij

**Pull request merged**
