### PR TITLE
Removed Unwanted Comments

### PR DESCRIPTION
**Pull request by arpit3018**
Removed unwanted comments.
1. Changes views.py in noticeboard, user, blog,  interview and study applications
2. Moreover changed urls.py from blog app and settings.py.

### CODE REVIEW

**Comment by monsij** [comment]
Hope that you have followed the contribution guidelines :-)

(Powered by [GitMate.io](https://gitmate.io))

**Comment by monsij** [comment]
"@gitmate-bot rebase"

**Comment by monsij** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by monsij** [comment]
@arpit3018 : Next time, do make a branch and initiate PRs from that branch and not from the master branch.

**Comment by monsij** [comment]
ack `96f4104`

**Comment by arpit3018** [comment]
Sure. I would make a branch and would initiate PR. Thanks.

**Pull request merged**
