### PR TITLE
Chanakya link updated

### PR DESCRIPTION
**Pull request by rahulotwani**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?

### New Feature Submissions:

1. [x] Does your submission pass build tests locally?
2. [x] Have you indented your code locally prior to submission?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by monsij** [comment]
Hope that you have followed the contribution guidelines. Please don't make a request anywhere to get a review. One of the maintainers will get back to it within a day or so. 😃

(Powered by [GitMate.io](https://gitmate.io))

**Comment by rahulotwani** [comment]
please review now

**Comment by monsij** [comment]
@rahulotwani I can still see changes in  `README.md` made here 😄

**Comment by monsij** [comment]
@rahulotwani : Resolve the conflicts and squash your commits

**Pull request closed without merging**
