### PR TITLE
Add Internship and Placement feature

### PR DESCRIPTION
**Pull request by gutsytechster**
This adds the facility to add internship and placments through
django admin panel which will be displayed on the respective page.
It also adds dynamice pages for more details regarding an internship
or placement.

closes https://github.com/monsij/StudentPortal/issues/43

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?

### New Feature Submissions:

1. [x] Does your submission pass build tests locally?
2. [x] Have you indented your code locally prior to submission?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by monsij** [comment]
Hope that you have followed the contribution guidelines. Please don't make a request anywhere to get a review. One of the maintainers will get back to it within a day or so. 😃

(Powered by [GitMate.io](https://gitmate.io))

**Comment by monsij** [comment]
Finally the most awaited PR came 😄 ! @gutsytechster

**Comment by monsij** [comment]
A few changes to be made: @gutsytechster 

-  Remove "experience needed" from both internships and placements. If required they will be provided under additional information.

-  **The pages of the internships and placements are visible without login. This has to be changed as this information should not be public**

-  Try providing the boxes for internships and placements with soft round edges with some good combination of colour. (not green actually 😄 )

-  Remove the joining date column entirely, as it is subject to change lately.

-  Add test location for internship as well. **If possible try to increase the word limit to 50**.

-  Run a check to see if scrolling among list of companies is working or not on mobile devices.

- Add a href button to each company entry(both internship and placement) . (Later this will point to the google-form for interested people).

-  A label to show if currently applying is open or not.

_**Last two things(label and href button) are to be made visible on the outer page i.e on `/interview` page**_

🛩 Lastly, a very good approach to handle all these . Simply Great! 🎉

**Comment by gutsytechster** [comment]
Sure @monsij. I'll correct them soon.
Just UI changes might take some extra time.

**Comment by gutsytechster** [comment]
And the thing about the 3rd point, do you mean the outer `/interview` page? or the table which is shown for each internship and placement?

**Comment by monsij** [comment]
> Sure @monsij. I'll correct them soon.
> Just UI changes might take some extra time.

Ok the UI changes can be handled in a separate issue then. Resolve rest

**Comment by monsij** [comment]
> And the thing about the 3rd point, do you mean the outer `/interview` page? or the table which is shown for each internship and placement?

Didn't get you

**Comment by monsij** [comment]
ack `7158c2c`

**Pull request merged**
